name: 'Build - Android'
description: 'Build - Android'
inputs:
  CONFIGURATION:
    required: false
    default: 'Release'
  DOTNET_CORE_VERSION: 
    required: false
    default: '10.x'
  GITHUB_TOKEN:
    required: true
  VERSION:
    required: true
  ASSEMBLYSEMVER:
    required: true
  ANDROID_KEYSTORE_BASE64:
    required: true
  ANDROID_KEYSTORE_PASSWORD:
    required: true
  ANDROID_KEY_ALIAS:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.DOTNET_CORE_VERSION }}

    - name: Restore Workloads
      run: dotnet workload restore
      shell: bash

    - name: Build
      run: dotnet build --configuration ${{ inputs.CONFIGURATION }} /p:Version=${{ inputs.VERSION }} /p:AssemblyVersion=${{ inputs.ASSEMBLYSEMVER }}
      shell: bash

    - name: Test
      run: dotnet test --configuration ${{ inputs.CONFIGURATION }} --no-build
      shell: bash

    - name: Decode Keystore
      run: |
        echo "${{ inputs.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > ${{ github.workspace }}/keystore.jks
      shell: bash

    - name: Publish
      run: |
        dotnet publish ${{ github.workspace }}/src/Blackjack --configuration ${{ inputs.CONFIGURATION }} -f net10.0-android --output ${{ github.workspace }}/publish-android \
          /p:Version=${{ inputs.VERSION }} \
          /p:AssemblyVersion=${{ inputs.ASSEMBLYSEMVER }} \
          /p:AndroidKeyStore=true \
          /p:AndroidSigningKeyStore=${{ github.workspace }}/keystore.jks \
          /p:AndroidSigningKeyAlias=${{ inputs.ANDROID_KEY_ALIAS }} \
          /p:AndroidSigningKeyPass=${{ inputs.ANDROID_KEYSTORE_PASSWORD }} \
          /p:AndroidSigningStorePass=${{ inputs.ANDROID_KEYSTORE_PASSWORD }}
      shell: bash

    - name: Upload Android Artifacts
      uses: actions/upload-artifact@v5
      with:
        name: android-release
        path: |
          ${{ github.workspace }}/publish-android/*-Signed.apk
          ${{ github.workspace }}/publish-android/*-Signed.aab
